"""
Refresh-token issuance, rotation, and revocation.

Every refresh token belongs to a "family" (a rotation lineage started at
login). On each successful /auth/refresh, the presented token is revoked and
a new one is issued in its place, carrying the same family_id. Presenting an
already-revoked token again is treated as theft (a stolen, already-rotated
token being replayed) and revokes the entire family, forcing that device
lineage to log in again.
"""

import hashlib
import uuid
from datetime import datetime, timedelta, timezone
from typing import Optional, TypedDict

from fastapi import HTTPException, status
from sqlalchemy import select, update
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config.settings import settings
from app.core.security.jwt import (
    create_access_token,
    create_refresh_token,
    decode_refresh_token,
)
from app.modules.account.service import is_within_grace_period, reactivate_account
from app.modules.auth.models import RefreshToken
from app.modules.users.models import User

_INVALID_REFRESH_DETAIL = "Invalid or expired refresh token."


class TokenPairDict(TypedDict):
    access_token: str
    refresh_token: str
    token_type: str


def _hash_token(token: str) -> str:
    return hashlib.sha256(token.encode()).hexdigest()


def _clip(value: Optional[str], length: int) -> Optional[str]:
    return value[:length] if value else None


async def _mint(
    db: AsyncSession,
    user_id: uuid.UUID,
    family_id: uuid.UUID,
    user_agent: Optional[str],
    ip_address: Optional[str],
    jti: Optional[uuid.UUID] = None,
) -> TokenPairDict:
    """Create a new access/refresh pair and persist the refresh token's row.
    Does not commit — caller controls the transaction boundary. `jti` can be
    pre-generated by the caller (e.g. rotation, to record it as
    replaced_by_jti on the old row before this one is even inserted)."""
    jti = jti or uuid.uuid4()
    access_token = create_access_token(user_id=str(user_id))
    refresh_token = create_refresh_token(
        user_id=str(user_id), jti=jti, family_id=family_id
    )
    expires_at = datetime.now(timezone.utc) + timedelta(
        days=settings.REFRESH_TOKEN_EXPIRE_DAYS
    )
    db.add(
        RefreshToken(
            user_id=user_id,
            jti=jti,
            family_id=family_id,
            token_hash=_hash_token(refresh_token),
            expires_at=expires_at,
            user_agent=_clip(user_agent, 255),
            ip_address=_clip(ip_address, 64),
        )
    )
    return {
        "access_token": access_token,
        "refresh_token": refresh_token,
        "token_type": "bearer",
    }


async def issue_token_pair(
    db: AsyncSession,
    user: User,
    user_agent: Optional[str] = None,
    ip_address: Optional[str] = None,
) -> TokenPairDict:
    """Issue a brand-new token family — called on register/login/token."""
    pair = await _mint(db, user.id, uuid.uuid4(), user_agent, ip_address)
    await db.commit()
    return pair


async def rotate_refresh_token(
    db: AsyncSession,
    refresh_token: str,
    user_agent: Optional[str] = None,
    ip_address: Optional[str] = None,
) -> TokenPairDict:
    """Validate, rotate, and return a new pair. Raises 401 on any failure."""
    payload = decode_refresh_token(refresh_token)
    invalid = HTTPException(
        status_code=status.HTTP_401_UNAUTHORIZED, detail=_INVALID_REFRESH_DETAIL
    )
    if payload is None:
        raise invalid

    try:
        jti = uuid.UUID(payload.get("jti", ""))
        family_id = uuid.UUID(payload.get("family_id", ""))
        user_id = uuid.UUID(payload.get("sub", ""))
    except ValueError:
        raise invalid

    result = await db.execute(select(RefreshToken).where(RefreshToken.jti == jti))
    row = result.scalar_one_or_none()
    if row is None or row.token_hash != _hash_token(refresh_token):
        raise invalid

    if row.revoked_at is not None:
        # Reuse of an already-rotated token — treat as theft, kill the family.
        await db.execute(
            update(RefreshToken)
            .where(
                RefreshToken.family_id == row.family_id,
                RefreshToken.revoked_at.is_(None),
            )
            .values(revoked_at=datetime.now(timezone.utc))
        )
        await db.commit()
        raise invalid

    now = datetime.now(timezone.utc)
    if row.expires_at < now:
        raise invalid

    user = await db.get(User, user_id)
    if user is None:
        raise invalid
    if not user.is_active:
        if is_within_grace_period(user):
            await reactivate_account(db, user)
        else:
            raise invalid

    new_jti = uuid.uuid4()
    row.revoked_at = now
    row.replaced_by_jti = new_jti
    db.add(row)

    pair = await _mint(db, user.id, family_id, user_agent, ip_address, jti=new_jti)
    await db.commit()
    return pair


async def revoke_refresh_token(db: AsyncSession, refresh_token: str) -> None:
    """Best-effort, idempotent revocation for /auth/logout. Never raises —
    an already-invalid/expired/malformed token is treated as already logged
    out, since logout must not leak token validity."""
    payload = decode_refresh_token(refresh_token)
    if payload is None:
        return
    try:
        jti = uuid.UUID(payload.get("jti", ""))
    except ValueError:
        return

    result = await db.execute(select(RefreshToken).where(RefreshToken.jti == jti))
    row = result.scalar_one_or_none()
    if row is not None and row.revoked_at is None:
        row.revoked_at = datetime.now(timezone.utc)
        db.add(row)
        await db.commit()


async def revoke_all_user_tokens(db: AsyncSession, user_id: uuid.UUID) -> None:
    """Log out of all devices — revoke every live refresh token for a user."""
    await db.execute(
        update(RefreshToken)
        .where(RefreshToken.user_id == user_id, RefreshToken.revoked_at.is_(None))
        .values(revoked_at=datetime.now(timezone.utc))
    )
    await db.commit()
